#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@118.114.244.93:31521:dsemr
#    username: DSHIS_MAIN
#    password: DSHIS_MAIN
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.202:1521:orcl
    username: HIS
    password: HIS
#    url: jdbc:oracle:thin:@118.114.244.93:31521:dsemr    TJ TJ



mybatis:
  mapper-locations: classpath*:/mapper/*.xml